# Generated by Django 3.2 on 2022-04-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='objectID',
        ),
    ]
