# Generated by Django 3.2 on 2022-04-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_itemdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdiscount',
            name='discount_price',
        ),
    ]
