# Generated by Django 3.2 on 2022-04-15 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_itemdiscount_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='discount_procent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
