# Generated by Django 3.2 on 2022-04-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_itemdiscount_discount_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdiscount',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
