# Generated by Django 3.2 on 2022-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
