# Generated by Django 3.2 on 2022-04-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
