# Generated by Django 3.2 on 2022-04-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_total',
        ),
    ]
