# Generated by Django 3.2 on 2022-04-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_orderitem_order_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True),
        ),
    ]
